
export const categoryOptions = [
    { value: "💰 Income - Salary", label: "💰 Income - Salary" },
    { value: "💼 Income - Freelance", label: "💼 Income - Freelance" },
    { value: "🎁 Income - Gift", label: "🎁 Income - Gift" },
    { value: "📈 Income - Investment", label: "📈 Income - Investment" },
    { value: "↩️ Income - Refund", label: "↩️ Income - Refund" },
    { value: "🏆 Income - Bonus", label: "🏆 Income - Bonus" },

    { value: "🛒 Groceries", label: "🛒 Groceries" },
    { value: "🍽️ Restaurant", label: "🍽️ Restaurant" },
    { value: "☕ Cafe & Coffee", label: "☕ Cafe & Coffee" },
    { value: "🥡 Takeout", label: "🥡 Takeout" },
    { value: "🍷 Alcohol & Bars", label: "🍷 Alcohol & Bars" },
    { value: "🚚 Food Delivery", label: "🚚 Food Delivery" },

    { value: "⛽ Fuel", label: "⛽ Fuel" },
    { value: "🚇 Public Transport", label: "🚇 Public Transport" },
    { value: "🚕 Taxi / Ride Share", label: "🚕 Taxi / Ride Share" },
    { value: "🅿️ Parking", label: "🅿️ Parking" },
    { value: "🔧 Car Maintenance", label: "🔧 Car Maintenance" },
    { value: "🚗 Car Insurance", label: "🚗 Car Insurance" },

    { value: "🏠 Rent", label: "🏠 Rent" },
    { value: "🏡 Mortgage", label: "🏡 Mortgage" },
    { value: "💡 Utilities", label: "💡 Utilities" },
    { value: "🌐 Internet & Cable", label: "🌐 Internet & Cable" },
    { value: "📱 Phone Bill", label: "📱 Phone Bill" },
    { value: "🔨 Home Repairs", label: "🔨 Home Repairs" },
    { value: "🛋️ Furniture & Decor", label: "🛋️ Furniture & Decor" },

    { value: "🎬 Streaming Services", label: "🎬 Streaming Services" },
    { value: "🎵 Music Subscription", label: "🎵 Music Subscription" },
    { value: "☁️ Cloud Storage", label: "☁️ Cloud Storage" },
    { value: "💪 Gym Membership", label: "💪 Gym Membership" },
    { value: "💻 Software Subscription", label: "💻 Software Subscription" },
    { value: "📰 News & Magazine", label: "📰 News & Magazine" },

    { value: "👕 Clothing", label: "👕 Clothing" },
    { value: "📱 Electronics", label: "📱 Electronics" },
    { value: "🏠 Home Goods", label: "🏠 Home Goods" },
    { value: "💄 Beauty & Cosmetics", label: "💄 Beauty & Cosmetics" },
    { value: "💊 Pharmacy & Health", label: "💊 Pharmacy & Health" },
    { value: "🐾 Pet Supplies", label: "🐾 Pet Supplies" },
    { value: "🎮 Games & Hobbies", label: "🎮 Games & Hobbies" },

    { value: "🏥 Doctor Visit", label: "🏥 Doctor Visit" },
    { value: "🦷 Dentist", label: "🦷 Dentist" },
    { value: "💊 Medication", label: "💊 Medication" },
    { value: "🛡️ Health Insurance", label: "🛡️ Health Insurance" },
    { value: "🧠 Therapy", label: "🧠 Therapy" },
    { value: "🧘 Wellness & Spa", label: "🧘 Wellness & Spa" },

    { value: "🎬 Movies & Cinema", label: "🎬 Movies & Cinema" },
    { value: "🎵 Concerts & Events", label: "🎵 Concerts & Events" },
    { value: "🎮 Gaming", label: "🎮 Gaming" },
    { value: "📚 Books & Audiobooks", label: "📚 Books & Audiobooks" },
    { value: "⚽ Sports Events", label: "⚽ Sports Events" },
    { value: "🏛️ Museums & Art", label: "🏛️ Museums & Art" },

    { value: "✈️ Flights", label: "✈️ Flights" },
    { value: "🏨 Hotels & Accommodation", label: "🏨 Hotels & Accommodation" },
    { value: "🚗 Rental Car", label: "🚗 Rental Car" },
    { value: "🏖️ Vacation Package", label: "🏖️ Vacation Package" },
    { value: "🧳 Luggage & Gear", label: "🧳 Luggage & Gear" },

    { value: "🎓 Tuition", label: "🎓 Tuition" },
    { value: "📚 Online Courses", label: "📚 Online Courses" },
    { value: "📖 Textbooks", label: "📖 Textbooks" },
    { value: "🔧 Workshop & Seminar", label: "🔧 Workshop & Seminar" },

    { value: "📄 Taxes", label: "📄 Taxes" },
    { value: "💳 Credit Card Payment", label: "💳 Credit Card Payment" },
    { value: "🏦 Loan Payment", label: "🏦 Loan Payment" },
    { value: "👶 Childcare", label: "👶 Childcare" },

    { value: "🏦 Transfer to Savings", label: "🏦 Transfer to Savings" },
    { value: "📊 Transfer to Investment", label: "📊 Transfer to Investment" },
    { value: "👥 Transfer to Friend", label: "👥 Transfer to Friend" },

    { value: "⚠️ Bank Fees", label: "⚠️ Bank Fees" },
    { value: "🙏 Charity & Donation", label: "🙏 Charity & Donation" },
    { value: "📦 Miscellaneous", label: "📦 Miscellaneous" },
]