
export const categoryOptions = [
    { value: "💰 Income - Salary", label: "💰 Income - Salary" },
    { value: "💼 Income - Freelance", label: "💼 Income - Freelance" },
    { value: "🎁 Income - Gift", label: "🎁 Income - Gift" },
    { value: "📈 Income - Investment", label: "📈 Income - Investment" },
    { value: "↩️ Income - Refund", label: "↩️ Income - Refund" },
    { value: "🏆 Income - Bonus", label: "🏆 Income - Bonus" },

    { value: "🛒 Groceries", label: "🛒 Groceries" },
    { value: "🍽️ Restaurant", label: "🍽️ Restaurant" },
    { value: "☕ Cafe & Coffee", label: "☕ Cafe & Coffee" },
    { value: "🥡 Takeout", label: "🥡 Takeout" },
    { value: "🍷 Alcohol & Bars", label: "🍷 Alcohol & Bars" },
    { value: "🚚 Food Delivery", label: "🚚 Food Delivery" },

    { value: "⛽ Fuel", label: "⛽ Fuel" },
    { value: "🚇 Public Transport", label: "🚇 Public Transport" },
    { value: "🚕 Taxi / Ride Share", label: "🚕 Taxi / Ride Share" },
    { value: "🅿️ Parking", label: "🅿️ Parking" },
    { value: "🔧 Car Maintenance", label: "🔧 Car Maintenance" },
    { value: "🚗 Car Insurance", label: "🚗 Car Insurance" },

    { value: "🏠 Rent", label: "🏠 Rent" },
    { value: "🏡 Mortgage", label: "🏡 Mortgage" },
    { value: "💡 Utilities", label: "💡 Utilities" },
    { value: "🌐 Internet & Cable", label: "🌐 Internet & Cable" },
    { value: "📱 Phone Bill", label: "📱 Phone Bill" },
    { value: "🔨 Home Repairs", label: "🔨 Home Repairs" },
    { value: "🛋️ Furniture & Decor", label: "🛋️ Furniture & Decor" },

    { value: "🎬 Streaming Services", label: "🎬 Streaming Services" },
    { value: "🎵 Music Subscription", label: "🎵 Music Subscription" },
    { value: "☁️ Cloud Storage", label: "☁️ Cloud Storage" },
    { value: "💪 Gym Membership", label: "💪 Gym Membership" },
    { value: "💻 Software Subscription", label: "💻 Software Subscription" },
    { value: "📰 News & Magazine", label: "📰 News & Magazine" },

    { value: "👕 Clothing", label: "👕 Clothing" },
    { value: "📱 Electronics", label: "📱 Electronics" },
    { value: "🏠 Home Goods", label: "🏠 Home Goods" },
    { value: "💄 Beauty & Cosmetics", label: "💄 Beauty & Cosmetics" },
    { value: "💊 Pharmacy & Health", label: "💊 Pharmacy & Health" },
    { value: "🐾 Pet Supplies", label: "🐾 Pet Supplies" },
    { value: "🎮 Games & Hobbies", label: "🎮 Games & Hobbies" },

    { value: "🏥 Doctor Visit", label: "🏥 Doctor Visit" },
    { value: "🦷 Dentist", label: "🦷 Dentist" },
    { value: "💊 Medication", label: "💊 Medication" },
    { value: "🛡️ Health Insurance", label: "🛡️ Health Insurance" },
    { value: "🧠 Therapy", label: "🧠 Therapy" },
    { value: "🧘 Wellness & Spa", label: "🧘 Wellness & Spa" },

    { value: "🎬 Movies & Cinema", label: "🎬 Movies & Cinema" },
    { value: "🎵 Concerts & Events", label: "🎵 Concerts & Events" },
    { value: "🎮 Gaming", label: "🎮 Gaming" },
    { value: "📚 Books & Audiobooks", label: "📚 Books & Audiobooks" },
    { value: "⚽ Sports Events", label: "⚽ Sports Events" },
    { value: "🏛️ Museums & Art", label: "🏛️ Museums & Art" },

    { value: "✈️ Flights", label: "✈️ Flights" },
    { value: "🏨 Hotels & Accommodation", label: "🏨 Hotels & Accommodation" },
    { value: "🚗 Rental Car", label: "🚗 Rental Car" },
    { value: "🏖️ Vacation Package", label: "🏖️ Vacation Package" },
    { value: "🧳 Luggage & Gear", label: "🧳 Luggage & Gear" },

    { value: "🎓 Tuition", label: "🎓 Tuition" },
    { value: "📚 Online Courses", label: "📚 Online Courses" },
    { value: "📖 Textbooks", label: "📖 Textbooks" },
    { value: "🔧 Workshop & Seminar", label: "🔧 Workshop & Seminar" },

    { value: "📄 Taxes", label: "📄 Taxes" },
    { value: "💳 Credit Card Payment", label: "💳 Credit Card Payment" },
    { value: "🏦 Loan Payment", label: "🏦 Loan Payment" },
    { value: "👶 Childcare", label: "👶 Childcare" },

    { value: "🏦 Transfer to Savings", label: "🏦 Transfer to Savings" },
    { value: "📊 Transfer to Investment", label: "📊 Transfer to Investment" },
    { value: "👥 Transfer to Friend", label: "👥 Transfer to Friend" },

    { value: "⚠️ Bank Fees", label: "⚠️ Bank Fees" },
    { value: "🙏 Charity & Donation", label: "🙏 Charity & Donation" },
    { value: "📦 Miscellaneous", label: "📦 Miscellaneous" },
]

export const currencyList = [
    {
        label: "Major Currencies",
        options: [
            { value: "USD", label: "🇺🇸 USD - US Dollar" },
            { value: "EUR", label: "🇪🇺 EUR - Euro" },
            { value: "GBP", label: "🇬🇧 GBP - British Pound" },
            { value: "JPY", label: "🇯🇵 JPY - Japanese Yen" },
        ],
    },
    {
        label: "🇪🇺 European",
        options: [
            { value: "CHF", label: "🇨🇭 CHF - Swiss Franc" },
            { value: "SEK", label: "🇸🇪 SEK - Swedish Krona" },
            { value: "NOK", label: "🇳🇴 NOK - Norwegian Krone" },
            { value: "DKK", label: "🇩🇰 DKK - Danish Krone" },
            { value: "PLN", label: "🇵🇱 PLN - Polish Złoty" },
            { value: "CZK", label: "🇨🇿 CZK - Czech Koruna" },
            { value: "HUF", label: "🇭🇺 HUF - Hungarian Forint" },
            { value: "RON", label: "🇷🇴 RON - Romanian Leu" },
            { value: "BGN", label: "🇧🇬 BGN - Bulgarian Lev" },
            { value: "RSD", label: "🇷🇸 RSD - Serbian Dinar" },
            { value: "HRK", label: "🇭🇷 HRK - Croatian Kuna" },
            { value: "ISK", label: "🇮🇸 ISK - Icelandic Króna" },
        ],
    },
    {
        label: "Asian",
        options: [
            { value: "CNY", label: "🇨🇳 CNY - Chinese Yuan" },
            { value: "KRW", label: "🇰🇷 KRW - South Korean Won" },
            { value: "SGD", label: "🇸🇬 SGD - Singapore Dollar" },
            { value: "HKD", label: "🇭🇰 HKD - Hong Kong Dollar" },
            { value: "INR", label: "🇮🇳 INR - Indian Rupee" },
            { value: "THB", label: "🇹🇭 THB - Thai Baht" },
            { value: "MYR", label: "🇲🇾 MYR - Malaysian Ringgit" },
            { value: "IDR", label: "🇮🇩 IDR - Indonesian Rupiah" },
            { value: "PHP", label: "🇵🇭 PHP - Philippine Peso" },
            { value: "VND", label: "🇻🇳 VND - Vietnamese Dong" },
            { value: "TWD", label: "🇹🇼 TWD - Taiwan Dollar" },
        ],
    },
    {
        label: "🇦🇲 Americas & Oceania",
        options: [
            { value: "CAD", label: "🇨🇦 CAD - Canadian Dollar" },
            { value: "AUD", label: "🇦🇺 AUD - Australian Dollar" },
            { value: "NZD", label: "🇳🇿 NZD - New Zealand Dollar" },
            { value: "BRL", label: "🇧🇷 BRL - Brazilian Real" },
            { value: "MXN", label: "🇲🇽 MXN - Mexican Peso" },
            { value: "ARS", label: "🇦🇷 ARS - Argentine Peso" },
            { value: "CLP", label: "🇨🇱 CLP - Chilean Peso" },
            { value: "COP", label: "🇨🇴 COP - Colombian Peso" },
            { value: "PEN", label: "🇵🇪 PEN - Peruvian Sol" },
        ],
    },
    {
        label: "🇹🇷 Middle East & Africa",
        options: [
            { value: "TRY", label: "🇹🇷 TRY - Turkish Lira" },
            { value: "AED", label: "🇦🇪 AED - UAE Dirham" },
            { value: "SAR", label: "🇸🇦 SAR - Saudi Riyal" },
            { value: "ILS", label: "🇮🇱 ILS - Israeli Shekel" },
            { value: "ZAR", label: "🇿🇦 ZAR - South African Rand" },
            { value: "EGP", label: "🇪🇬 EGP - Egyptian Pound" },
            { value: "NGN", label: "🇳🇬 NGN - Nigerian Naira" },
            { value: "QAR", label: "🇶🇦 QAR - Qatari Riyal" },
            { value: "KWD", label: "🇰🇼 KWD - Kuwaiti Dinar" },
            { value: "OMR", label: "🇴🇲 OMR - Omani Rial" },
            { value: "BHD", label: "🇧🇭 BHD - Bahraini Dinar" },
        ],
    },
    {
        label: "🇷🇺 Post-Soviet",
        options: [
            { value: "RUB", label: "🇷🇺 RUB - Russian Ruble" },
            { value: "UAH", label: "🇺🇦 UAH - Ukrainian Hryvnia" },
            { value: "KZT", label: "🇰🇿 KZT - Kazakhstani Tenge" },
            { value: "GEL", label: "🇬🇪 GEL - Georgian Lari" },
            { value: "AMD", label: "🇦🇲 AMD - Armenian Dram" },
            { value: "AZN", label: "🇦🇿 AZN - Azerbaijani Manat" },
            { value: "BYN", label: "🇧🇾 BYN - Belarusian Ruble" },
            { value: "UZS", label: "🇺🇿 UZS - Uzbekistani Som" },
            { value: "KGS", label: "🇰🇬 KGS - Kyrgyzstani Som" },
            { value: "TJS", label: "🇹🇯 TJS - Tajikistani Somoni" },
            { value: "MDL", label: "🇲🇩 MDL - Moldovan Leu" },
        ],
    },
]