
export const categoryOptions = [
    { value: "💰 Income - Salary", label: "💰 Income - Salary" },
    { value: "💼 Income - Freelance", label: "💼 Income - Freelance" },
    { value: "🎁 Income - Gift", label: "🎁 Income - Gift" },
    { value: "📈 Income - Investment", label: "📈 Income - Investment" },
    { value: "↩️ Income - Refund", label: "↩️ Income - Refund" },
    { value: "🏆 Income - Bonus", label: "🏆 Income - Bonus" },

    { value: "🛒 Groceries", label: "🛒 Groceries" },
    { value: "🍽️ Restaurant", label: "🍽️ Restaurant" },
    { value: "☕ Cafe & Coffee", label: "☕ Cafe & Coffee" },
    { value: "🥡 Takeout", label: "🥡 Takeout" },
    { value: "🍷 Alcohol & Bars", label: "🍷 Alcohol & Bars" },
    { value: "🚚 Food Delivery", label: "🚚 Food Delivery" },

    { value: "⛽ Fuel", label: "⛽ Fuel" },
    { value: "🚇 Public Transport", label: "🚇 Public Transport" },
    { value: "🚕 Taxi / Ride Share", label: "🚕 Taxi / Ride Share" },
    { value: "🅿️ Parking", label: "🅿️ Parking" },
    { value: "🔧 Car Maintenance", label: "🔧 Car Maintenance" },
    { value: "🚗 Car Insurance", label: "🚗 Car Insurance" },

    { value: "🏠 Rent", label: "🏠 Rent" },
    { value: "🏡 Mortgage", label: "🏡 Mortgage" },
    { value: "💡 Utilities", label: "💡 Utilities" },
    { value: "🌐 Internet & Cable", label: "🌐 Internet & Cable" },
    { value: "📱 Phone Bill", label: "📱 Phone Bill" },
    { value: "🔨 Home Repairs", label: "🔨 Home Repairs" },
    { value: "🛋️ Furniture & Decor", label: "🛋️ Furniture & Decor" },

    { value: "🎬 Streaming Services", label: "🎬 Streaming Services" },
    { value: "🎵 Music Subscription", label: "🎵 Music Subscription" },
    { value: "☁️ Cloud Storage", label: "☁️ Cloud Storage" },
    { value: "💪 Gym Membership", label: "💪 Gym Membership" },
    { value: "💻 Software Subscription", label: "💻 Software Subscription" },
    { value: "📰 News & Magazine", label: "📰 News & Magazine" },

    { value: "👕 Clothing", label: "👕 Clothing" },
    { value: "📱 Electronics", label: "📱 Electronics" },
    { value: "🏠 Home Goods", label: "🏠 Home Goods" },
    { value: "💄 Beauty & Cosmetics", label: "💄 Beauty & Cosmetics" },
    { value: "💊 Pharmacy & Health", label: "💊 Pharmacy & Health" },
    { value: "🐾 Pet Supplies", label: "🐾 Pet Supplies" },
    { value: "🎮 Games & Hobbies", label: "🎮 Games & Hobbies" },

    { value: "🏥 Doctor Visit", label: "🏥 Doctor Visit" },
    { value: "🦷 Dentist", label: "🦷 Dentist" },
    { value: "💊 Medication", label: "💊 Medication" },
    { value: "🛡️ Health Insurance", label: "🛡️ Health Insurance" },
    { value: "🧠 Therapy", label: "🧠 Therapy" },
    { value: "🧘 Wellness & Spa", label: "🧘 Wellness & Spa" },

    { value: "🎬 Movies & Cinema", label: "🎬 Movies & Cinema" },
    { value: "🎵 Concerts & Events", label: "🎵 Concerts & Events" },
    { value: "🎮 Gaming", label: "🎮 Gaming" },
    { value: "📚 Books & Audiobooks", label: "📚 Books & Audiobooks" },
    { value: "⚽ Sports Events", label: "⚽ Sports Events" },
    { value: "🏛️ Museums & Art", label: "🏛️ Museums & Art" },

    { value: "✈️ Flights", label: "✈️ Flights" },
    { value: "🏨 Hotels & Accommodation", label: "🏨 Hotels & Accommodation" },
    { value: "🚗 Rental Car", label: "🚗 Rental Car" },
    { value: "🏖️ Vacation Package", label: "🏖️ Vacation Package" },
    { value: "🧳 Luggage & Gear", label: "🧳 Luggage & Gear" },

    { value: "🎓 Tuition", label: "🎓 Tuition" },
    { value: "📚 Online Courses", label: "📚 Online Courses" },
    { value: "📖 Textbooks", label: "📖 Textbooks" },
    { value: "🔧 Workshop & Seminar", label: "🔧 Workshop & Seminar" },

    { value: "📄 Taxes", label: "📄 Taxes" },
    { value: "💳 Credit Card Payment", label: "💳 Credit Card Payment" },
    { value: "🏦 Loan Payment", label: "🏦 Loan Payment" },
    { value: "👶 Childcare", label: "👶 Childcare" },

    { value: "🏦 Transfer to Savings", label: "🏦 Transfer to Savings" },
    { value: "📊 Transfer to Investment", label: "📊 Transfer to Investment" },
    { value: "👥 Transfer to Friend", label: "👥 Transfer to Friend" },

    { value: "⚠️ Bank Fees", label: "⚠️ Bank Fees" },
    { value: "🙏 Charity & Donation", label: "🙏 Charity & Donation" },
    { value: "📦 Miscellaneous", label: "📦 Miscellaneous" },
]

export const categoryOptionsNo = [
    { value: "Income - Salary", label: "Income - Salary" },
    { value: "Income - Freelance", label: "Income - Freelance" },
    { value: "Income - Gift", label: "Income - Gift" },
    { value: "Income - Investment", label: "Income - Investment" },
    { value: "Income - Refund", label: "Income - Refund" },
    { value: "Income - Bonus", label: "Income - Bonus" },

    { value: "Groceries", label: "Groceries" },
    { value: "Restaurant", label: "Restaurant" },
    { value: "Cafe & Coffee", label: "Cafe & Coffee" },
    { value: "Takeout", label: "Takeout" },
    { value: "Alcohol & Bars", label: "Alcohol & Bars" },
    { value: "Food Delivery", label: "Food Delivery" },

    { value: "Fuel", label: "Fuel" },
    { value: "Public Transport", label: "Public Transport" },
    { value: "Taxi / Ride Share", label: "Taxi / Ride Share" },
    { value: "Parking", label: "Parking" },
    { value: "Car Maintenance", label: "Car Maintenance" },
    { value: "Car Insurance", label: "Car Insurance" },

    { value: "Rent", label: "Rent" },
    { value: "Mortgage", label: "Mortgage" },
    { value: "Utilities", label: "Utilities" },
    { value: "Internet & Cable", label: "Internet & Cable" },
    { value: "Phone Bill", label: "Phone Bill" },
    { value: "Home Repairs", label: "Home Repairs" },
    { value: "Furniture & Decor", label: "Furniture & Decor" },

    { value: "Streaming Services", label: "Streaming Services" },
    { value: "Music Subscription", label: "Music Subscription" },
    { value: "Cloud Storage", label: "Cloud Storage" },
    { value: "Gym Membership", label: "Gym Membership" },
    { value: "Software Subscription", label: "Software Subscription" },
    { value: "News & Magazine", label: "News & Magazine" },

    { value: "Clothing", label: "Clothing" },
    { value: "Electronics", label: "Electronics" },
    { value: "Home Goods", label: "Home Goods" },
    { value: "Beauty & Cosmetics", label: "Beauty & Cosmetics" },
    { value: "Pharmacy & Health", label: "Pharmacy & Health" },
    { value: "Pet Supplies", label: "Pet Supplies" },
    { value: "Games & Hobbies", label: "Games & Hobbies" },

    { value: "Doctor Visit", label: "Doctor Visit" },
    { value: "Dentist", label: "Dentist" },
    { value: "Medication", label: "Medication" },
    { value: "Health Insurance", label: "Health Insurance" },
    { value: "Therapy", label: "Therapy" },
    { value: "Wellness & Spa", label: "Wellness & Spa" },

    { value: "Movies & Cinema", label: "Movies & Cinema" },
    { value: "Concerts & Events", label: "Concerts & Events" },
    { value: "Gaming", label: "Gaming" },
    { value: "Books & Audiobooks", label: "Books & Audiobooks" },
    { value: "Sports Events", label: "Sports Events" },
    { value: "Museums & Art", label: "Museums & Art" },

    { value: "Flights", label: "Flights" },
    { value: "Hotels & Accommodation", label: "Hotels & Accommodation" },
    { value: "Rental Car", label: "Rental Car" },
    { value: "Vacation Package", label: "Vacation Package" },
    { value: "Luggage & Gear", label: "Luggage & Gear" },

    { value: "Tuition", label: "Tuition" },
    { value: "Online Courses", label: "Online Courses" },
    { value: "Textbooks", label: "Textbooks" },
    { value: "Workshop & Seminar", label: "Workshop & Seminar" },

    { value: "Taxes", label: "Taxes" },
    { value: "Credit Card Payment", label: "Credit Card Payment" },
    { value: "Loan Payment", label: "Loan Payment" },
    { value: "Childcare", label: "Childcare" },

    { value: "Transfer to Savings", label: "Transfer to Savings" },
    { value: "Transfer to Investment", label: "Transfer to Investment" },
    { value: "Transfer to Friend", label: "Transfer to Friend" },

    { value: "Bank Fees", label: "Bank Fees" },
    { value: "Charity & Donation", label: "Charity & Donation" },
    { value: "Miscellaneous", label: "Miscellaneous" },
]

export const currencyList = [
    {
        label: "Major Currencies",
        options: [
            { value: "USD", label: "🇺🇸 USD - US Dollar" },
            { value: "EUR", label: "🇪🇺 EUR - Euro" },
            { value: "GBP", label: "🇬🇧 GBP - British Pound" },
            { value: "JPY", label: "🇯🇵 JPY - Japanese Yen" },
        ],
    },
    {
        label: "🇪🇺 European",
        options: [
            { value: "CHF", label: "🇨🇭 CHF - Swiss Franc" },
            { value: "SEK", label: "🇸🇪 SEK - Swedish Krona" },
            { value: "NOK", label: "🇳🇴 NOK - Norwegian Krone" },
            { value: "DKK", label: "🇩🇰 DKK - Danish Krone" },
            { value: "PLN", label: "🇵🇱 PLN - Polish Złoty" },
            { value: "CZK", label: "🇨🇿 CZK - Czech Koruna" },
            { value: "HUF", label: "🇭🇺 HUF - Hungarian Forint" },
            { value: "RON", label: "🇷🇴 RON - Romanian Leu" },
            { value: "BGN", label: "🇧🇬 BGN - Bulgarian Lev" },
            { value: "RSD", label: "🇷🇸 RSD - Serbian Dinar" },
            { value: "HRK", label: "🇭🇷 HRK - Croatian Kuna" },
            { value: "ISK", label: "🇮🇸 ISK - Icelandic Króna" },
        ],
    },
    {
        label: "Asian",
        options: [
            { value: "CNY", label: "🇨🇳 CNY - Chinese Yuan" },
            { value: "KRW", label: "🇰🇷 KRW - South Korean Won" },
            { value: "SGD", label: "🇸🇬 SGD - Singapore Dollar" },
            { value: "HKD", label: "🇭🇰 HKD - Hong Kong Dollar" },
            { value: "INR", label: "🇮🇳 INR - Indian Rupee" },
            { value: "THB", label: "🇹🇭 THB - Thai Baht" },
            { value: "MYR", label: "🇲🇾 MYR - Malaysian Ringgit" },
            { value: "IDR", label: "🇮🇩 IDR - Indonesian Rupiah" },
            { value: "PHP", label: "🇵🇭 PHP - Philippine Peso" },
            { value: "VND", label: "🇻🇳 VND - Vietnamese Dong" },
            { value: "TWD", label: "🇹🇼 TWD - Taiwan Dollar" },
        ],
    },
    {
        label: "🇦🇲 Americas & Oceania",
        options: [
            { value: "CAD", label: "🇨🇦 CAD - Canadian Dollar" },
            { value: "AUD", label: "🇦🇺 AUD - Australian Dollar" },
            { value: "NZD", label: "🇳🇿 NZD - New Zealand Dollar" },
            { value: "BRL", label: "🇧🇷 BRL - Brazilian Real" },
            { value: "MXN", label: "🇲🇽 MXN - Mexican Peso" },
            { value: "ARS", label: "🇦🇷 ARS - Argentine Peso" },
            { value: "CLP", label: "🇨🇱 CLP - Chilean Peso" },
            { value: "COP", label: "🇨🇴 COP - Colombian Peso" },
            { value: "PEN", label: "🇵🇪 PEN - Peruvian Sol" },
        ],
    },
    {
        label: "🇹🇷 Middle East & Africa",
        options: [
            { value: "TRY", label: "🇹🇷 TRY - Turkish Lira" },
            { value: "AED", label: "🇦🇪 AED - UAE Dirham" },
            { value: "SAR", label: "🇸🇦 SAR - Saudi Riyal" },
            { value: "ILS", label: "🇮🇱 ILS - Israeli Shekel" },
            { value: "ZAR", label: "🇿🇦 ZAR - South African Rand" },
            { value: "EGP", label: "🇪🇬 EGP - Egyptian Pound" },
            { value: "NGN", label: "🇳🇬 NGN - Nigerian Naira" },
            { value: "QAR", label: "🇶🇦 QAR - Qatari Riyal" },
            { value: "KWD", label: "🇰🇼 KWD - Kuwaiti Dinar" },
            { value: "OMR", label: "🇴🇲 OMR - Omani Rial" },
            { value: "BHD", label: "🇧🇭 BHD - Bahraini Dinar" },
        ],
    },
    {
        label: "🇷🇺 Post-Soviet",
        options: [
            { value: "RUB", label: "🇷🇺 RUB - Russian Ruble" },
            { value: "UAH", label: "🇺🇦 UAH - Ukrainian Hryvnia" },
            { value: "KZT", label: "🇰🇿 KZT - Kazakhstani Tenge" },
            { value: "GEL", label: "🇬🇪 GEL - Georgian Lari" },
            { value: "AMD", label: "🇦🇲 AMD - Armenian Dram" },
            { value: "AZN", label: "🇦🇿 AZN - Azerbaijani Manat" },
            { value: "BYN", label: "🇧🇾 BYN - Belarusian Ruble" },
            { value: "UZS", label: "🇺🇿 UZS - Uzbekistani Som" },
            { value: "KGS", label: "🇰🇬 KGS - Kyrgyzstani Som" },
            { value: "TJS", label: "🇹🇯 TJS - Tajikistani Somoni" },
            { value: "MDL", label: "🇲🇩 MDL - Moldovan Leu" },
        ],
    },
]

export const categoryOptionsRu = [
    { value: "💰 Income - Salary", label: "💰 Зарплата" },
    { value: "💼 Income - Freelance", label: "💼 Фриланс" },
    { value: "🎁 Income - Gift", label: "🎁 Подарок" },
    { value: "📈 Income - Investment", label: "📈 Инвестиции" },
    { value: "↩️ Income - Refund", label: "↩️ Возврат" },
    { value: "🏆 Income - Bonus", label: "🏆 Бонус" },

    { value: "🛒 Groceries", label: "🛒 Продукты" },
    { value: "🍽️ Restaurant", label: "🍽️ Ресторан" },
    { value: "☕ Cafe & Coffee", label: "☕ Кофе" },
    { value: "🥡 Takeout", label: "🥡 Еда на вынос" },
    { value: "🍷 Alcohol & Bars", label: "🍷 Алкоголь" },
    { value: "🚚 Food Delivery", label: "🚚 Доставка еды" },

    { value: "⛽ Fuel", label: "⛽ Топливо" },
    { value: "🚇 Public Transport", label: "🚇 Общественный транспорт" },
    { value: "🚕 Taxi / Ride Share", label: "🚕 Такси" },
    { value: "🅿️ Parking", label: "🅿️ Парковка" },
    { value: "🔧 Car Maintenance", label: "🔧 Ремонт авто" },
    { value: "🚗 Car Insurance", label: "🚗 Страховка авто" },

    { value: "🏠 Rent", label: "🏠 Аренда" },
    { value: "🏡 Mortgage", label: "🏡 Ипотека" },
    { value: "💡 Utilities", label: "💡 Коммунальные услуги" },
    { value: "🌐 Internet & Cable", label: "🌐 Интернет" },
    { value: "📱 Phone Bill", label: "📱 Телефон" },
    { value: "🔨 Home Repairs", label: "🔨 Ремонт дома" },
    { value: "🛋️ Furniture & Decor", label: "🛋️ Мебель" },

    { value: "🎬 Streaming Services", label: "🎬 Стриминг" },
    { value: "🎵 Music Subscription", label: "🎵 Музыка" },
    { value: "☁️ Cloud Storage", label: "☁️ Облачное хранилище" },
    { value: "💪 Gym Membership", label: "💪 Спортзал" },
    { value: "💻 Software Subscription", label: "💻 Программы" },
    { value: "📰 News & Magazine", label: "📰 Подписка на новости" },

    { value: "👕 Clothing", label: "👕 Одежда" },
    { value: "📱 Electronics", label: "📱 Электроника" },
    { value: "🏠 Home Goods", label: "🏠 Товары для дома" },
    { value: "💄 Beauty & Cosmetics", label: "💄 Косметика" },
    { value: "💊 Pharmacy & Health", label: "💊 Аптека" },
    { value: "🐾 Pet Supplies", label: "🐾 Товары для животных" },
    { value: "🎮 Games & Hobbies", label: "🎮 Хобби" },

    { value: "🏥 Doctor Visit", label: "🏥 Врач" },
    { value: "🦷 Dentist", label: "🦷 Стоматолог" },
    { value: "💊 Medication", label: "💊 Лекарства" },
    { value: "🛡️ Health Insurance", label: "🛡️ Страховка здоровья" },
    { value: "🧠 Therapy", label: "🧠 Психотерапия" },
    { value: "🧘 Wellness & Spa", label: "🧘 СПА" },

    { value: "🎬 Movies & Cinema", label: "🎬 Кино" },
    { value: "🎵 Concerts & Events", label: "🎵 Концерты" },
    { value: "🎮 Gaming", label: "🎮 Игры" },
    { value: "📚 Books & Audiobooks", label: "📚 Книги" },
    { value: "⚽ Sports Events", label: "⚽ Спортивные мероприятия" },
    { value: "🏛️ Museums & Art", label: "🏛️ Музеи" },

    { value: "✈️ Flights", label: "✈️ Авиабилеты" },
    { value: "🏨 Hotels & Accommodation", label: "🏨 Отели" },
    { value: "🚗 Rental Car", label: "🚗 Аренда авто" },
    { value: "🏖️ Vacation Package", label: "🏖️ Путешествия" },
    { value: "🧳 Luggage & Gear", label: "🧳 Чемоданы" },

    { value: "🎓 Tuition", label: "🎓 Обучение" },
    { value: "📚 Online Courses", label: "📚 Онлайн-курсы" },
    { value: "📖 Textbooks", label: "📖 Учебники" },
    { value: "🔧 Workshop & Seminar", label: "🔧 Семинары" },

    { value: "📄 Taxes", label: "📄 Налоги" },
    { value: "💳 Credit Card Payment", label: "💳 Оплата картой" },
    { value: "🏦 Loan Payment", label: "🏦 Кредит" },
    { value: "👶 Childcare", label: "👶 Детский сад" },

    { value: "🏦 Transfer to Savings", label: "🏦 Перевод в сбережения" },
    { value: "📊 Transfer to Investment", label: "📊 Перевод в инвестиции" },
    { value: "👥 Transfer to Friend", label: "👥 Перевод другу" },

    { value: "⚠️ Bank Fees", label: "⚠️ Банковские комиссии" },
    { value: "🙏 Charity & Donation", label: "🙏 Благотворительность" },
    { value: "📦 Miscellaneous", label: "📦 Разное" },
]

export const categoryOptionsNoRu = [
    { value: "Income - Salary", label: "Зарплата" },
    { value: "Income - Freelance", label: "Фриланс" },
    { value: "Income - Gift", label: "Подарок" },
    { value: "Income - Investment", label: "Инвестиции" },
    { value: "Income - Refund", label: "Возврат" },
    { value: "Income - Bonus", label: "Бонус" },

    { value: "Groceries", label: "Продукты" },
    { value: "Restaurant", label: "Ресторан" },
    { value: "Cafe & Coffee", label: "Кофе" },
    { value: "Takeout", label: "Еда на вынос" },
    { value: "Alcohol & Bars", label: "Алкоголь" },
    { value: "Food Delivery", label: "Доставка еды" },

    { value: "Fuel", label: "Топливо" },
    { value: "Public Transport", label: "Общественный транспорт" },
    { value: "Taxi / Ride Share", label: "Такси" },
    { value: "Parking", label: "Парковка" },
    { value: "Car Maintenance", label: "Ремонт авто" },
    { value: "Car Insurance", label: "Страховка авто" },

    { value: "Rent", label: "Аренда" },
    { value: "Mortgage", label: "Ипотека" },
    { value: "Utilities", label: "Коммунальные услуги" },
    { value: "Internet & Cable", label: "Интернет" },
    { value: "Phone Bill", label: "Телефон" },
    { value: "Home Repairs", label: "Ремонт дома" },
    { value: "Furniture & Decor", label: "Мебель" },

    { value: "Streaming Services", label: "Стриминг" },
    { value: "Music Subscription", label: "Музыка" },
    { value: "Cloud Storage", label: "Облачное хранилище" },
    { value: "Gym Membership", label: "Спортзал" },
    { value: "Software Subscription", label: "Программы" },
    { value: "News & Magazine", label: "Подписка на новости" },

    { value: "Clothing", label: "Одежда" },
    { value: "Electronics", label: "Электроника" },
    { value: "Home Goods", label: "Товары для дома" },
    { value: "Beauty & Cosmetics", label: "Косметика" },
    { value: "Pharmacy & Health", label: "Аптека" },
    { value: "Pet Supplies", label: "Товары для животных" },
    { value: "Games & Hobbies", label: "Хобби" },

    { value: "Doctor Visit", label: "Врач" },
    { value: "Dentist", label: "Стоматолог" },
    { value: "Medication", label: "Лекарства" },
    { value: "Health Insurance", label: "Страховка здоровья" },
    { value: "Therapy", label: "Психотерапия" },
    { value: "Wellness & Spa", label: "СПА" },

    { value: "Movies & Cinema", label: "Кино" },
    { value: "Concerts & Events", label: "Концерты" },
    { value: "Gaming", label: "Игры" },
    { value: "Books & Audiobooks", label: "Книги" },
    { value: "Sports Events", label: "Спортивные мероприятия" },
    { value: "Museums & Art", label: "Музеи" },

    { value: "Flights", label: "Авиабилеты" },
    { value: "Hotels & Accommodation", label: "Отели" },
    { value: "Rental Car", label: "Аренда авто" },
    { value: "Vacation Package", label: "Путешествия" },
    { value: "Luggage & Gear", label: "Чемоданы" },

    { value: "Tuition", label: "Обучение" },
    { value: "Online Courses", label: "Онлайн-курсы" },
    { value: "Textbooks", label: "Учебники" },
    { value: "Workshop & Seminar", label: "Семинары" },

    { value: "Taxes", label: "Налоги" },
    { value: "Credit Card Payment", label: "Оплата картой" },
    { value: "Loan Payment", label: "Кредит" },
    { value: "Childcare", label: "Детский сад" },

    { value: "Transfer to Savings", label: "Перевод в сбережения" },
    { value: "Transfer to Investment", label: "Перевод в инвестиции" },
    { value: "Transfer to Friend", label: "Перевод другу" },

    { value: "Bank Fees", label: "Банковские комиссии" },
    { value: "Charity & Donation", label: "Благотворительность" },
    { value: "Miscellaneous", label: "Разное" },
]

export const currencyListRu = [
    {
        label: "Основные валюты",
        options: [
            { value: "USD", label: "🇺🇸 USD - Доллар США" },
            { value: "EUR", label: "🇪🇺 EUR - Евро" },
            { value: "GBP", label: "🇬🇧 GBP - Британский фунт" },
            { value: "JPY", label: "🇯🇵 JPY - Японская иена" },
        ],
    },
    {
        label: "🇪🇺 Европейские валюты",
        options: [
            { value: "CHF", label: "🇨🇭 CHF - Швейцарский франк" },
            { value: "SEK", label: "🇸🇪 SEK - Шведская крона" },
            { value: "NOK", label: "🇳🇴 NOK - Норвежская крона" },
            { value: "DKK", label: "🇩🇰 DKK - Датская крона" },
            { value: "PLN", label: "🇵🇱 PLN - Польский злотый" },
            { value: "CZK", label: "🇨🇿 CZK - Чешская крона" },
            { value: "HUF", label: "🇭🇺 HUF - Венгерский форинт" },
            { value: "RON", label: "🇷🇴 RON - Румынский лей" },
            { value: "BGN", label: "🇧🇬 BGN - Болгарский лев" },
            { value: "RSD", label: "🇷🇸 RSD - Сербский динар" },
            { value: "HRK", label: "🇭🇷 HRK - Хорватская куна" },
            { value: "ISK", label: "🇮🇸 ISK - Исландская крона" },
        ],
    },
    {
        label: "Азиатские валюты",
        options: [
            { value: "CNY", label: "🇨🇳 CNY - Китайский юань" },
            { value: "KRW", label: "🇰🇷 KRW - Южнокорейская вона" },
            { value: "SGD", label: "🇸🇬 SGD - Сингапурский доллар" },
            { value: "HKD", label: "🇭🇰 HKD - Гонконгский доллар" },
            { value: "INR", label: "🇮🇳 INR - Индийская рупия" },
            { value: "THB", label: "🇹🇭 THB - Тайский бат" },
            { value: "MYR", label: "🇲🇾 MYR - Малайзийский ринггит" },
            { value: "IDR", label: "🇮🇩 IDR - Индонезийская рупия" },
            { value: "PHP", label: "🇵🇭 PHP - Филиппинское песо" },
            { value: "VND", label: "🇻🇳 VND - Вьетнамский донг" },
            { value: "TWD", label: "🇹🇼 TWD - Тайваньский доллар" },
        ],
    },
    {
        label: "🇦🇲 Америка и Океания",
        options: [
            { value: "CAD", label: "🇨🇦 CAD - Канадский доллар" },
            { value: "AUD", label: "🇦🇺 AUD - Австралийский доллар" },
            { value: "NZD", label: "🇳🇿 NZD - Новозеландский доллар" },
            { value: "BRL", label: "🇧🇷 BRL - Бразильский реал" },
            { value: "MXN", label: "🇲🇽 MXN - Мексиканское песо" },
            { value: "ARS", label: "🇦🇷 ARS - Аргентинское песо" },
            { value: "CLP", label: "🇨🇱 CLP - Чилийское песо" },
            { value: "COP", label: "🇨🇴 COP - Колумбийское песо" },
            { value: "PEN", label: "🇵🇪 PEN - Перуанский соль" },
        ],
    },
    {
        label: "🇹🇷 Ближний Восток и Африка",
        options: [
            { value: "TRY", label: "🇹🇷 TRY - Турецкая лира" },
            { value: "AED", label: "🇦🇪 AED - Дирхам ОАЭ" },
            { value: "SAR", label: "🇸🇦 SAR - Саудовский риял" },
            { value: "ILS", label: "🇮🇱 ILS - Израильский шекель" },
            { value: "ZAR", label: "🇿🇦 ZAR - Южноафриканский рэнд" },
            { value: "EGP", label: "🇪🇬 EGP - Египетский фунт" },
            { value: "NGN", label: "🇳🇬 NGN - Нигерийская найра" },
            { value: "QAR", label: "🇶🇦 QAR - Катарский риял" },
            { value: "KWD", label: "🇰🇼 KWD - Кувейтский динар" },
            { value: "OMR", label: "🇴🇲 OMR - Оманский риал" },
            { value: "BHD", label: "🇧🇭 BHD - Бахрейнский динар" },
        ],
    },
    {
        label: "🇷🇺 Постсоветское пространство",
        options: [
            { value: "RUB", label: "🇷🇺 RUB - Российский рубль" },
            { value: "UAH", label: "🇺🇦 UAH - Украинская гривна" },
            { value: "KZT", label: "🇰🇿 KZT - Казахстанский тенге" },
            { value: "GEL", label: "🇬🇪 GEL - Грузинский лари" },
            { value: "AMD", label: "🇦🇲 AMD - Армянский драм" },
            { value: "AZN", label: "🇦🇿 AZN - Азербайджанский манат" },
            { value: "BYN", label: "🇧🇾 BYN - Белорусский рубль" },
            { value: "UZS", label: "🇺🇿 UZS - Узбекский сум" },
            { value: "KGS", label: "🇰🇬 KGS - Киргизский сом" },
            { value: "TJS", label: "🇹🇯 TJS - Таджикский сомони" },
            { value: "MDL", label: "🇲🇩 MDL - Молдавский лей" },
        ],
    },
]