export const getCurrencySymbol = (currencyCode: string): string => {
    const symbols: Record<string, string> = {
        USD: '$',
        EUR: '€',
        GBP: '£',
        JPY: '¥',
        CNY: '¥',
        CHF: 'Fr',
        CAD: '$',
        AUD: '$',
        NZD: '$',
        KRW: '₩',
        SGD: '$',
        HKD: '$',
        SEK: 'kr',
        NOK: 'kr',
        DKK: 'kr',
        PLN: 'zł',
        CZK: 'Kč',
        HUF: 'Ft',
        ILS: '₪',
        TRY: '₺',
        RUB: '₽',
        INR: '₹',
        BRL: 'R$',
        MXN: '$',
        ZAR: 'R',
        AED: 'د.إ',
        SAR: '﷼',
        THB: '฿',
        MYR: 'RM',
        IDR: 'Rp',
        PHP: '₱',
        VND: '₫',
        EGP: 'E£',
        NGN: '₦',
        PKR: '₨',
        UAH: '₴',
        KZT: '₸',
        GEL: '₾',
        AMD: '֏',
        AZN: '₼',
        BYN: 'Br',
        RSD: 'дин',
        BGN: 'лв',
        RON: 'lei',
        HRK: 'kn',
        ISK: 'kr',
        TWD: 'NT$',
        ARS: '$',
        CLP: '$',
        COP: '$',
        PEN: 'S/',
        QAR: '﷼',
        KWD: 'د.ك',
        OMR: '﷼',
        BHD: '.د.ب',
        UZS: 'soʻm',
        KGS: 'с',
        TJS: 'SM',
        MDL: 'L',
    };

    return symbols[currencyCode] || currencyCode;
}